
apiVersion: v1
kind: Namespace
metadata:
  name: evohome-bigquery-exporter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: evohome-bigquery-exporter
  namespace: evohome-bigquery-exporter
  labels:
    app: evohome-bigquery-exporter
---
apiVersion: v1
kind: Secret
metadata:
  name: evohome-bigquery-exporter-credentials
  namespace: evohome-bigquery-exporter
  labels:
    app: evohome-bigquery-exporter
type: Opaque
data:
  username: ${EVOHOME_USERNAME}
  password: ${EVOHOME_PASSWORD}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: evohome-bigquery-exporter
  namespace: evohome-bigquery-exporter
  labels:
    app: evohome-bigquery-exporter
spec:
  schedule: '${SCHEDULE}'
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  suspend: false  
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      template:
        metadata:
          labels:
            app: evohome-bigquery-exporter
        spec:
          restartPolicy: OnFailure
          serviceAccount: evohome-bigquery-exporter
          containers:
          - name: evohome-bigquery-exporter
            image: jsalverda/evohome-bigquery-exporter:${CONTAINER_TAG}
            imagePullPolicy: IfNotPresent
            env:
            - name: "EVOHOME_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: evohome-bigquery-exporter-credentials
                  key: username
            - name: "EVOHOME_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: evohome-bigquery-exporter-credentials
                  key: password
            resources:
              requests:
                cpu: 100m
                memory: 200Mi
              limits:
                cpu: 200m
                memory: 200Mi
          terminationGracePeriodSeconds: 300