apiVersion: v1
kind: Namespace
metadata:
  name: evohome-bigquery-exporter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: evohome-bigquery-exporter
  namespace: evohome-bigquery-exporter
  labels:
    app: evohome-bigquery-exporter
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: evohome-bigquery-exporter
  namespace: evohome-bigquery-exporter
  labels:
    app: evohome-bigquery-exporter
spec:
  schedule: '${SCHEDULE}'
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  suspend: false  
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 0
      activeDeadlineSeconds: 240
      template:
        metadata:
          labels:
            app: evohome-bigquery-exporter
        spec:
          restartPolicy: Never
          serviceAccount: evohome-bigquery-exporter
          containers:
          - name: evohome-bigquery-exporter
            image: jsalverda/evohome-bigquery-exporter:${CONTAINER_TAG}
            env:
            - name: "NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: "EVOHOME_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: evohome-bigquery-exporter-credentials
                  key: username
            - name: "EVOHOME_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: evohome-bigquery-exporter-credentials
                  key: password
            - name: "BQ_PROJECT_ID"
              valueFrom:
                configMapKeyRef:
                  name: evohome-bigquery-exporter-configs
                  key: bq-project-id
            - name: "BQ_DATASET"
              valueFrom:
                configMapKeyRef:
                  name: evohome-bigquery-exporter-configs
                  key: bq-dataset
            - name: "BQ_TABLE"
              valueFrom:
                configMapKeyRef:
                  name: evohome-bigquery-exporter-configs
                  key: bq-table
            - name: "OUTDOOR_ZONE_NAME"
              valueFrom:
                configMapKeyRef:
                  name: evohome-bigquery-exporter-configs
                  key: outdoor-zone-name
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/secrets/keyfile.json"
            resources:
              requests:
                cpu: 100m
                memory: 200Mi
              limits:
                cpu: 200m
                memory: 200Mi
            volumeMounts:
            - name: secrets
              mountPath: /secrets
            - name: state
              mountPath: /state
          terminationGracePeriodSeconds: 300
          volumes:
          - name: secrets
            secret:
              secretName: evohome-bigquery-exporter-credentials
          - name: state
            configMap:
              name: evohome-hgi80-listener-state