apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: evohome-bigquery-exporter
  namespace: evohome-bigquery-exporter
  labels:
    app: evohome-bigquery-exporter
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - secrets
  verbs:
  - list
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: evohome-bigquery-exporter
  namespace: evohome-bigquery-exporter
  labels:
    app: evohome-bigquery-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: evohome-bigquery-exporter
subjects:
- kind: ServiceAccount
  name: evohome-bigquery-exporter
  namespace: evohome-bigquery-exporter