apiVersion: v1
kind: Namespace
metadata:
  name: evohome-bigquery-exporter
---
apiVersion: v1
kind: Secret
metadata:
  name: evohome-bigquery-exporter-credentials
  namespace: evohome-bigquery-exporter
  labels:
    app: evohome-bigquery-exporter
type: Opaque
data:
  username: ${EVOHOME_USERNAME}
  password: ${EVOHOME_PASSWORD}
  keyfile.json: ${GCP_SERVICE_ACCOUNT_KEYFILE}