apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "evohome-bigquery-exporter.fullname" . }}
  labels:
    {{- include "evohome-bigquery-exporter.labels" . | nindent 4 }}
data:
  bq-project-id: {{ .Values.config.bqProjectID | toString }}
  bq-dataset: {{ .Values.config.bqDataset | toString }}
  bq-table: {{ .Values.config.bqTable | toString }}
  outdoor-zone-name: {{ .Values.config.outdoorZoneName | toString }}