{{- if .Values.rbac.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "evohome-bigquery-exporter.fullname" . }}
  labels:
    {{- include "evohome-bigquery-exporter.labels" . | nindent 4 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - secrets
  verbs:
  - list
  - update
  - watch
{{- end -}}